AWSTemplateFormatVersion: 2010-09-09
Description: 'Creates the required parameters in Parameter Store (qs-000000)'
Parameters:
  DeploymentPrefix:
    Type: String
    Description: ''
  DeploymentName:
    Type: String
    Description: ''
  DeploymentS3BucketName:
    Type: String
    Description: ''
  DeploymentS3KeyPrefix:
    Type: String
    Description: ''
  EKSClusterName:
    Type: String
    Description: ''
  EKSClusterRegion:
    Type: String
    Description: ''
  QSS3BucketName:
    Type: String
    Description: ''
  QSS3BucketRegion:
    Type: String
    Description: ''
  QSS3KeyPrefix:
    Type: String
    Description: ''
Resources:
  # SSM Parameter Store entries
  DeploymentPrefixSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/deployment/prefix
      Description: Prefix to be used for the deployment
      Type: String
      Value: !Ref DeploymentPrefix
  DeploymentNameSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/deployment/name
      Description: Name to be used for the deployment combines the DeployementPrefix with a random string
      Type: String
      Value: !Ref DeploymentName
  DeploymentS3BucketNameSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/s3/bucketname
      Description: S3 bucket where the installation media and license are located
      Type: String
      Value: !Ref DeploymentS3BucketName
  DeploymentS3KeyPrefixSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/s3/keyprefix
      Description: S3 Key Prefix where the installation media and licensen are located
      Type: String
      Value: !Ref DeploymentS3KeyPrefix
  EKSClusterNameSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/eks/cluster/name
      Description: The name of the EKS Cluster for the deployment
      Type: String
      Value: !Ref EKSClusterName
  EKSClusterRegionSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/eks/cluster/region
      Description: The region of the EKS Cluster for the deployment
      Type: String
      Value: !Ref EKSClusterRegion
  EKSDeploymentNameSSMP:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${DeploymentName}/eks/deployment/name
      Description: The name of this EKS deployment
      Type: String
      Value: !Ref DeploymentName
  # Secrets Manager Secrets

  # Deployment Secrets
  sitecoreAdmin: 
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-admin
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreCollectionShardmapmanagerDatabase: 
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-collection-shardmapmanager-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "csdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreCoreDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-core-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "coredbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreDatabaseElasticPool:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-database-elastic-pool
      Description: Deployment Secret
      SecretString: !Sub '{"name":"${DeploymentName}-elastic-pool"}'
  sitecoreDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: !Sub '{"username": "dbuser","servername": "${DeploymentName}-db"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreExmMasterDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-exm-master-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "emdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreFormsDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-forms-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "fdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreIdentitycertificate:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-identitycertificate
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"string": "none"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreIdentity:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-identity
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: 'secret'
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreLicense:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-license
      Description: Deployment Secret
      SecretString: !Sub '{"string":"none"}'
  sitecoreMarketingAutomationDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-marketing-automation-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "mkdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreMasterDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-master-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "mdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreMessagingDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-messaging-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "msdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreProcessingEngineStorageDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-processing-engine-storage-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "pesdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreProcessingEngineTasksDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-processing-engine-tasks-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "petdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreProcessingPoolsDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-processing-pools-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "pdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreProcessingTasksDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-processing-tasks-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "ptdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreReferenceDataDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-reference-data-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "rddbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreReportingDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-reporting-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "rdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreReportingapi:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-reportingapi
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: 'key'
        PasswordLength: 96
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreSolrSonnectionStringXdb:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-solr-connection-xdb
      Description: Deployment Secret
      SecretString: !Sub '{"string":"http://solr:8983/solr/sit ecore_xdb;solrCloud=tr ue"}'
  sitecoreSolrSonnectionString:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-solr-connection
      Description: Deployment Secret
      SecretString: !Sub '{"string":"http://solr:8983/solr;sol rCloud=true"}'
  sitecoreTelerikencryption:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-telerikencryption
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: 'key'
        PasswordLength: 96
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  sitecoreWebDatabase:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Sub sc-${DeploymentName}-sitecore-web-database
      Description: Deployment Secret
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "wdbuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false

# Outputs:
#   CustomAmiName:
#     Description: The name of the Quick Start Sitecore custom AMI.
#     Value: !GetAtt CustomAmiName.Value
#   SCLocalResourcePath:
#     Description: The location of the Sitecore resources on the AMI.
#     Value: !GetAtt LocalResourcesPath.Value
#   QSLocalResourcePath:
#     Description: The location of the Quick Start resources on the AMI.
#     Value: !GetAtt LocalQuickStartResourcesPath.Value
#   InstanceCertificateLocation:
#     Description: Location of the Sitecore generated certificate in the S3 bucket.
#     Value: !Join
#       - ''
#       - - !GetAtt S3CertificatePrefix.Value
#         - !GetAtt ExportInstanceCertName.Value
#         - '.pfx'
#   SolrURL:
#     Description: The URL of the Solr instance.
#     Value: !GetAtt SolrUrl.Value
